name: untitled5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'

dependencies:

  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  http: ^1.1.0
  just_audio: ^0.9.36
  quran: ^1.2.2
  route_transitions: ^2.0.1
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/